### ISSUE TITLE
Error Playing Video on iOS 11

### ISSUE THREAD

**Issue by 08irfan** [vimeo/PlayerKit#30] opened 2018-03-05 06:40 UTC
Getting following errors while trying to load same URL multiple times in iOS 11
1)
Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;

2) Task <188925AF-FA5D-4310-BB4D-45CC9E45A41F>.<2> finished with error - code: -1002

**Comment by 08irfan** [comment] 2018-03-05 14:20
@ghking

**Comment by ghking** [comment] 2018-03-05 19:17
@08irfan What URL are you using?

**Comment by 08irfan** [comment] 2018-03-05 19:49
@ghking Thanks for response.
 Actually, I am loading videos in a tableview from an array of Vimeo URLs 
 example URL
https://player.vimeo.com/external/256018582.sd.mp4?s=d7e53d82cf5f6f7e31d4bbf999baec5cc95a2afc&profile_id=165&oauth2_token_id=1042216942

Videos loads a couple of times max or maybe less, after that errors start appearing on debugger/log screen.

` tempPost.player = [[RegularPlayer alloc] init];
                 tempPost.player.fillMode = FillModeFit;
                 AVAsset * asset = [AVAsset assetWithURL:[NSURL URLWithString:tempPost.lowVideoQuality.link]];
                 [tempPost.player set:asset];
                 tempPost.player.delegate = self;`

Above code is called in a loop.
Below is screen shot of log screen.
![screen shot 2018-03-06 at 12 47 12 am](https://user-images.githubusercontent.com/6177881/36996194-fb136824-20d7-11e8-8011-50d5068ee7c4.png)

**Comment by 08irfan** [comment] 2018-03-08 13:56
@ghking any update please?

**Comment by ghking** [comment] 2018-03-08 15:10
@08irfan I'm not able to reproduce that issue. Do you have specific steps?

**Comment by moazzam-adda247** [comment] 2018-09-25 05:45
@ghking I am also getting the same error what I am using is an asset with header like this:
   `let asset = AVURLAsset(url: url, options: ["AVURLAssetHTTPHeaderFieldsKey":header])`
I think it is something related to ios11 only. you can check this post:
[Stackoverflow](https://stackoverflow.com/questions/46434004/cant-play-mp3-file-over-http-via-avplayer?rq=1)

**Comment by jenniferlim** [comment] 2018-10-29 16:22
@moazzam-adda247, @08irfan - I'm not able to reproduce this issue neither on iOS11. Could you provide specific steps?

**Comment by nicolelehrer** [comment] 2019-01-07 18:48
@moazzam-adda247 @08irfan closing this out, but please let us know if you have further issues.

**Closed as completed by nicolelehrer** 2019-01-07 18:48 UTC
